<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="QuestPDF" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZnunyStats.Domain\ZnunyStats.Domain.csproj" />
  </ItemGroup>

</Project>
